use_frameworks!

platform :ios, '8.0'

target 'SPPopupSDK_Example' do
  pod 'SPPopupSDK', :path => '../'

  target 'SPPopupSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
